# Generated by Django 2.2.6 on 2020-01-03 23:55

from django.db import migrations, models
import django.db.models.deletion
import dt_content.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('content', dt_content.fields.SummernoteField(blank=True, null=True)),
                ('plain_text', models.BooleanField(default=False, editable=False)),
                ('last_known_location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(default=False)),
                ('key', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('static_location', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselBlock',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dt_content.ContentBlock')),
            ],
            bases=('dt_content.contentblock',),
        ),
        migrations.CreateModel(
            name='RichTextBlock',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dt_content.ContentBlock')),
                ('content', dt_content.fields.SummernoteField(blank=True, default='')),
            ],
            bases=('dt_content.contentblock',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('url_slug', models.SlugField(max_length=32)),
                ('disabled', models.BooleanField(default=False)),
                ('redirect_to', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dt_content.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=256)),
                ('static_location', models.URLField(null=True)),
                ('menu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_section', to='dt_content.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='contentblock',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_blocks', to='dt_content.ContentSection'),
        ),
        migrations.AddIndex(
            model_name='blurb',
            index=models.Index(fields=['identifier'], name='dt_content__identif_a63e57_idx'),
        ),
        migrations.AddIndex(
            model_name='blurb',
            index=models.Index(fields=['last_known_location', 'identifier'], name='dt_content__last_kn_1368e9_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['parent', 'url_slug'], name='dt_content__parent__8e384f_idx'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(parent__isnull=True), fields=('url_slug',), name='unique_parent_url_slug'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('parent', 'url_slug'), name='unique_child_url_slug'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='menu',
            order_with_respect_to='parent',
        ),
        migrations.AlterOrderWithRespectTo(
            name='contentblock',
            order_with_respect_to='section',
        ),
    ]
