# Generated by Django 2.2.6 on 2020-02-25 02:26

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dt_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to='image_blurbs')),
                ('placeholder', models.TextField(blank=True, default=None, help_text='Path to static placeholder image file', null=True)),
                ('last_known_location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='imageblurb',
            index=models.Index(fields=['identifier'], name='dt_content__identif_ef91ed_idx'),
        ),
        migrations.AddIndex(
            model_name='imageblurb',
            index=models.Index(fields=['last_known_location', 'identifier'], name='dt_content__last_kn_c9abca_idx'),
        ),
    ]
