#!/usr/bin/env bash

source venv/bin/activate
pip install -r requirements.txt
touch db.sqlite3
sudo chown www-data db.sqlite3
sudo chmod g+w db.sqlite3
python manage.py migrate
python manage.py collectstatic --noinput
python manage.py check
