# Generated by Django 2.2.3 on 2019-07-28 22:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_status_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date status modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CO", "Complete"),
                            ("IC", "Incomplete"),
                            ("MC", "Multiple Charges"),
                        ],
                        default="IC",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="price amount")),
                (
                    "currency",
                    models.CharField(
                        default="usd", max_length=3, verbose_name="currency"
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="quantity")),
                ("name", models.TextField(verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="key"
                    ),
                ),
                (
                    "prefilled_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="prefilled email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="stripe checkout id",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date completed"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                ("cancel_url", models.URLField(verbose_name="cancel url")),
                ("success_url", models.URLField(verbose_name="success_url")),
                (
                    "checkout",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_set",
                        to="django_stripe.Checkout",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(fields=["key"], name="django_stri_key_3a11dd_idx"),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["stripe_session_id", "date_created"],
                name="django_stri_stripe__cac092_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["date_created"], name="django_stri_date_cr_5e82fd_idx"
            ),
        ),
    ]
